micronaut:
  application:
    name: swagger-test
  server:
    port: 1001
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: ${application.api.swagger.path}/**
application:
  api:
    swagger:
      path: /api-docs/swagger
      version: 3.22.3
      layout: StandaloneLayout
      deepLinking: true
      urls:
        - name: swagger-test
          url: /api-docs/swagger/swagger-test-0.1.yml